default_stages: [commit]
default_language_version:
  python: python3.11
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0  # Use the ref you want to point to
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml

- repo: https://github.com/psf/black
  rev: 23.10.0
  hooks:
  - id: black
    language_version: python3

- repo: local
  hooks:
    - id: ruff # ruff should run before formatting tools like black https://beta.ruff.rs/docs/usage/
      name: ruff
      entry: ruff check . --exit-non-zero-on-fix
      pass_filenames: false
      always_run: true
      verbose: true
      language: system
      types: [python]
